[build]
  # Directory to change to before starting a build
  base = "project-gallery"
  
  # Directory that contains the deploy-ready HTML files and assets
  publish = "project-gallery/dist"
  
  # Build command
  command = "npm run prod-build"

# Serve data.json directly without redirects
[[headers]]
  for = "/data.json"
  [headers.values]
    Content-Type = "application/json"

# SPA fallback for all other routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
