[build]
  # Directory to change to before starting a build
  base = "project-gallery"
  
  # Directory that contains the deploy-ready HTML files and assets
  publish = "project-gallery/dist"
  
  # Build command
  command = "npm run prod-build"

[[redirects]]
  from = "/data.json"
  to = "/data.json"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
