# -*- coding: utf-8 -*-
"""Rebuilds src/html/components/navbar.html from the live inspiritai.com nav.

Pujan asked for the gallery's nav to match the main site, "pulled directly from it
live if possible". A *runtime* fetch is not possible - research.inspiritai.com asking
inspiritai.com for its markup is cross-origin and Squarespace sends no CORS header,
so the browser would block it. Doing it at build time gives the same result with no
runtime dependency and no CORS problem: run this, commit, and the nav is in sync.

    python sync-nav.py            # rewrite navbar.html from the live site
    python sync-nav.py --dry-run  # show what it would write
"""
import io, json, os, re, sys

from playwright.sync_api import sync_playwright

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, 'src', 'html', 'components', 'navbar.html')
SITE = 'https://www.inspiritai.com/'

JS = """() => {
  const seen = new Set();
  const out = [];
  document.querySelectorAll('.header-nav-item').forEach(n => {
    const a = n.querySelector(':scope > a');
    const raw = (a ? a.textContent : n.textContent) || '';
    const label = raw.trim().split(String.fromCharCode(10))[0].trim();
    if (!label || seen.has(label)) return;
    seen.add(label);
    const kids = [];
    n.querySelectorAll('.header-nav-folder-content a').forEach(k => {
      const t = (k.textContent || '').trim();
      if (t) kids.push({text: t, href: k.getAttribute('href')});
    });
    out.push({label: label, href: a ? a.getAttribute('href') : null, children: kids});
  });
  let cta = null;
  document.querySelectorAll('a').forEach(a => {
    const t = (a.textContent || '').trim();
    if (!cta && /^apply now$/i.test(t)) cta = {text: t, href: a.getAttribute('href')};
  });
  return {nav: out, cta: cta};
}"""


def absolute(href):
    if not href:
        return None
    if href.startswith(('http://', 'https://', 'mailto:', 'tel:')):
        return href
    return 'https://www.inspiritai.com' + ('' if href.startswith('/') else '/') + href


def esc(t):
    return (t or '').replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')


def build(nav, cta):
    lines = [
        '{# Generated by sync-nav.py from the live inspiritai.com header. #}',
        '{# Do not hand-edit - re-run `python sync-nav.py` to resync. #}',
        '<nav class="navbar navbar-expand-xl p-4 pe-5">',
        "  <a class=\"navbar-brand\" href=\"https://www.inspiritai.com\">"
        "<img class=\"nav-logo\" src={{ '../assets/images/logo.png' if isProject else 'assets/images/logo.png'}} alt=\"Inspirit AI\"></a>",
        '  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"'
        ' aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">',
        '      <span class="navbar-toggler-icon"></span>',
        '  </button>',
        '  <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">',
        '    <ul class="navbar-nav">',
    ]
    for i, item in enumerate(nav):
        label, href, kids = item['label'], absolute(item['href']), item['children']
        slug = re.sub(r'[^a-z0-9]+', '', label.lower()) or ('item%d' % i)
        if kids:
            top = href or absolute(kids[0]['href'])
            lines += [
                '      <li class="nav-item dropdown">',
                '        <a class="nav-link dropdown-toggle" href="%s" id="%sDropdown" role="button"'
                ' data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">' % (top, slug),
                '          %s' % esc(label),
                '        </a>',
                '        <div class="dropdown-menu" aria-labelledby="%sDropdown">' % slug,
            ]
            for k in kids:
                lines.append('          <a class="dropdown-item" href="%s">%s</a>'
                             % (absolute(k['href']), esc(k['text'])))
            lines += ['        </div>', '      </li>']
        else:
            lines += ['      <li class="nav-item">',
                      '        <a class="nav-link" href="%s">%s</a>' % (href, esc(label)),
                      '      </li>']
    if cta:
        # styled as a button to match the main site's header CTA
        lines += ['      <li class="nav-item nav-cta-item">',
                  '        <a class="nav-link nav-cta" href="%s">%s</a>' % (absolute(cta['href']), esc(cta['text'])),
                  '      </li>']
    lines += ['    </ul>', '  </div>', '</nav>', '']
    return '\n'.join(lines)


with sync_playwright() as pw:
    browser = pw.chromium.launch(channel='chrome')
    page = browser.new_page(viewport={'width': 1440, 'height': 900})
    page.goto(SITE, wait_until='domcontentloaded', timeout=90000)
    page.wait_for_timeout(2500)
    got = page.evaluate(JS)
    browser.close()

nav, cta = got['nav'], got['cta']
if not nav:
    sys.exit('could not read the nav from %s - leaving navbar.html untouched' % SITE)

print('top-level items pulled from the live site:')
for item in nav:
    print('  %-22s %-42s %d sub-links' % (item['label'], item['href'] or '(folder)', len(item['children'])))
print('  CTA: %s -> %s' % (cta['text'], cta['href']) if cta else '  (no Apply Now found)')

html = build(nav, cta)
if '--dry-run' in sys.argv:
    print('\n--- would write ---\n' + html)
else:
    io.open(OUT, 'w', encoding='utf-8', newline='\n').write(html)
    print('\nwrote %s (%d bytes)' % (OUT, len(html)))
